# Generated by Django 5.2.6 on 2025-10-18 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('listings', '0003_alter_listing_qa정보_alter_listing_버스정류장정보_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('진행률', models.IntegerField(default=0, verbose_name='진행률(%)')),
                ('평면도URL', models.TextField(blank=True, null=True, verbose_name='평면도 이미지 URL')),
                ('리포트URL', models.TextField(blank=True, null=True, verbose_name='임장 리포트 URL')),
                ('평가사메모', models.TextField(blank=True, null=True, verbose_name='평가사 메모')),
                ('시작일시', models.DateTimeField(auto_now_add=True, verbose_name='시작 일시')),
                ('수정일시', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('평가사ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_inspections', to='agents.agent', verbose_name='담당 평가사')),
            ],
            options={
                'verbose_name': '진행중인 임장',
                'verbose_name_plural': '진행중인 임장',
                'db_table': 'active_inspections',
                'ordering': ['-시작일시'],
            },
        ),
        migrations.CreateModel(
            name='InspectionCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('취소사유', models.TextField(verbose_name='취소 사유')),
                ('재요청여부', models.BooleanField(default=True, verbose_name='재요청 가능 여부')),
                ('취소일시', models.DateTimeField(auto_now_add=True, verbose_name='취소 일시')),
                ('임장ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='inspections.activeinspection', verbose_name='취소된 임장')),
                ('평가사ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent', verbose_name='취소한 평가사')),
            ],
            options={
                'verbose_name': '임장 취소',
                'verbose_name_plural': '임장 취소',
                'db_table': 'inspection_cancellations',
                'ordering': ['-취소일시'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('희망날짜', models.DateField(verbose_name='희망 임장 날짜')),
                ('연락처', models.CharField(max_length=20, verbose_name='연락처')),
                ('요청사항', models.TextField(blank=True, null=True, verbose_name='요청 사항')),
                ('매물제목', models.CharField(max_length=200, verbose_name='매물 제목')),
                ('매물주소', models.TextField(verbose_name='매물 주소')),
                ('가격정보', models.CharField(max_length=100, verbose_name='가격 정보 텍스트')),
                ('임장비', models.IntegerField(default=150000, verbose_name='임장비(원)')),
                ('매물이미지URL', models.TextField(blank=True, null=True, verbose_name='매물 대표 이미지 URL')),
                ('매물설명', models.TextField(blank=True, null=True, verbose_name='매물 설명')),
                ('특이사항', models.JSONField(blank=True, null=True, verbose_name='특이사항 목록')),
                ('현재사진URLs', models.JSONField(blank=True, null=True, verbose_name='현재 사진 URL 목록')),
                ('상태', models.CharField(choices=[('requested', '요청됨'), ('accepted', '수락됨'), ('rejected', '거절됨'), ('cancelled', '취소됨'), ('completed', '완료됨')], default='requested', max_length=20, verbose_name='요청 상태')),
                ('요청일시', models.DateTimeField(auto_now_add=True, verbose_name='요청 일시')),
                ('수락일시', models.DateTimeField(blank=True, null=True, verbose_name='수락 일시')),
                ('완료일시', models.DateTimeField(blank=True, null=True, verbose_name='완료 일시')),
                ('담당평가사ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspections', to='agents.agent', verbose_name='담당 평가사')),
                ('매물ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_requests', to='listings.listing', verbose_name='매물')),
                ('요청자ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_inspection_requests', to='users.userprofile', verbose_name='요청자')),
            ],
            options={
                'verbose_name': '임장 요청',
                'verbose_name_plural': '임장 요청',
                'db_table': 'inspection_requests',
                'ordering': ['-요청일시'],
            },
        ),
        migrations.AddField(
            model_name='activeinspection',
            name='요청ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_inspection', to='inspections.inspectionrequest', verbose_name='임장 요청'),
        ),
    ]
