# Generated by Django 5.2.6 on 2025-10-30 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('inspections', '0003_activeinspection_report_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveInspection',
            new_name='InspectionProgress',
        ),
        # 옵션 변경(표시용) - 스키마 변경 없음
        migrations.AlterModelOptions(
            name='inspectionprogress',
            options={'verbose_name': '임장 진행', 'verbose_name_plural': '임장 진행', 'ordering': ['-시작일시']},
        ),
        migrations.CreateModel(
            name='Floorplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('데이터', models.JSONField(blank=True, null=True, verbose_name='평면도 데이터')),
                ('이미지URL', models.TextField(blank=True, null=True, verbose_name='평면도 이미지 URL')),
                ('생성일시', models.DateTimeField(auto_now_add=True)),
                ('수정일시', models.DateTimeField(auto_now=True)),
                ('임장ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='floorplan', to='inspections.inspectionprogress', verbose_name='연결된 임장 진행')),
            ],
            options={
                'verbose_name': '평면도',
                'verbose_name_plural': '평면도',
                'db_table': 'inspection_floorplans',
            },
        ),
        migrations.AlterField(
            model_name='inspectioncancellation',
            name='임장ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='inspections.inspectionprogress', verbose_name='취소된 임장'),
        ),
    ]
