# Generated by Django 5.2.6 on 2025-10-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('시도', models.CharField(max_length=20, verbose_name='시도')),
                ('시군구', models.CharField(max_length=50, verbose_name='시군구')),
                ('읍면동', models.CharField(max_length=50, verbose_name='읍면동')),
                ('활성화여부', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역',
                'db_table': 'regions',
                'unique_together': {('시도', '시군구', '읍면동')},
            },
        ),
    ]
