# Generated by Django 5.2.6 on 2025-10-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='QA정보',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Q&A 정보'),
        ),
        migrations.AddField(
            model_name='property',
            name='노선다양성점수',
            field=models.IntegerField(blank=True, null=True, verbose_name='노선 다양성 점수(0-5)'),
        ),
        migrations.AddField(
            model_name='property',
            name='대중교통점수',
            field=models.IntegerField(blank=True, null=True, verbose_name='대중교통 편의성 점수(0-10)'),
        ),
        migrations.AddField(
            model_name='property',
            name='버스정류장정보',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='버스 정류장 정보'),
        ),
        migrations.AddField(
            model_name='property',
            name='이미지URLs',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='매물 이미지 URL 목록'),
        ),
        migrations.AddField(
            model_name='property',
            name='지하철역정보',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='지하철역 정보'),
        ),
        migrations.AddField(
            model_name='property',
            name='편의시설요약',
            field=models.TextField(blank=True, null=True, verbose_name='편의시설 및 상권 요약'),
        ),
    ]

