# Generated by Django 5.2.6 on 2025-10-18 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(max_length=200, verbose_name='공지 제목')),
                ('내용', models.TextField(verbose_name='공지 내용')),
                ('대상', models.CharField(choices=[('all', '전체'), ('user', '소비자'), ('agent', '평가사')], default='all', max_length=20, verbose_name='공지 대상')),
                ('신규여부', models.BooleanField(default=True, verbose_name='신규 여부')),
                ('활성화여부', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('작성일시', models.DateTimeField(auto_now_add=True, verbose_name='작성 일시')),
                ('수정일시', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('작성자ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'db_table': 'notices',
                'ordering': ['-작성일시'],
            },
        ),
    ]
