# Generated by Django 5.2.6 on 2025-10-15 09:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5179)),
                ('ufid', models.CharField(blank=True, db_column='UFID', max_length=34, null=True)),
                ('bjcd', models.CharField(blank=True, db_column='BJCD', max_length=10, null=True, verbose_name='법정동코드')),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=100, null=True, verbose_name='명칭')),
                ('divi', models.CharField(blank=True, db_column='DIVI', max_length=6, null=True, verbose_name='구분')),
                ('scls', models.CharField(blank=True, db_column='SCLS', max_length=8, null=True, verbose_name='통합코드')),
                ('fmta', models.CharField(blank=True, db_column='FMTA', max_length=9, null=True, verbose_name='제작정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '시도',
                'verbose_name_plural': '시도',
                'db_table': 'locations_korea"."sido_5179',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
