# Generated by Django 5.2.6 on 2025-10-19 05:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('정류장번호', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='정류장 번호')),
                ('정류장명', models.CharField(max_length=100, verbose_name='정류장 이름')),
                ('위치', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='정류장 위치')),
                ('정보수집일', models.DateField(blank=True, null=True, verbose_name='정보 수집 일')),
                ('모바일단축번호', models.CharField(blank=True, max_length=20, null=True, verbose_name='모바일 단축번호')),
                ('도시코드', models.CharField(blank=True, max_length=20, null=True, verbose_name='도시 코드')),
                ('도시명', models.CharField(blank=True, max_length=100, null=True, verbose_name='도시 이름')),
                ('관리도시명', models.CharField(blank=True, max_length=100, null=True, verbose_name='관리 도시 이름')),
            ],
            options={
                'verbose_name': '버스정류장',
                'verbose_name_plural': '버스정류장',
                'db_table': 'bus_stops',
                'ordering': ['정류장번호'],
            },
        ),
    ]
