# Generated by Django 5.2.6 on 2025-10-19 05:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_busstop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='위치',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='정류장 위치'),
        ),
    ]
