# Generated by Django 5.2.6 on 2025-10-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_busstop_위치'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('시도', models.CharField(max_length=20, verbose_name='시도')),
                ('시군구', models.CharField(max_length=50, verbose_name='시군구')),
                ('읍면동', models.CharField(max_length=50, verbose_name='읍면동')),
                ('활성화여부', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역',
                'db_table': 'regions',
                'ordering': ['시도', '시군구', '읍면동'],
                'unique_together': {('시도', '시군구', '읍면동')},
            },
        ),
        # regions 테이블이 이미 존재하므로 실제 CREATE TABLE을 수행하지 않음
        migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),  # No-op SQL
    ]

