# Generated by Django 5.2.6 on 2025-10-15 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('매물타입', models.CharField(choices=[('sale', '매매'), ('jeonse', '전세'), ('monthly', '월세')], max_length=10, verbose_name='매물 타입')),
                ('주택종류', models.CharField(choices=[('apartment', '아파트'), ('officetel', '오피스텔'), ('villa', '빌라'), ('oneroom', '원룸'), ('tworoom', '투룸'), ('duplex', '복층'), ('store', '상가'), ('office', '사무실')], max_length=20, verbose_name='주택 종류')),
                ('매매가', models.BigIntegerField(blank=True, null=True, verbose_name='매매 가격(원)')),
                ('전세보증금', models.BigIntegerField(blank=True, null=True, verbose_name='전세 보증금(원)')),
                ('월세보증금', models.BigIntegerField(blank=True, null=True, verbose_name='월세 보증금(원)')),
                ('월세', models.BigIntegerField(blank=True, null=True, verbose_name='월세 금액(원)')),
                ('주소', models.TextField(verbose_name='매물 전체 주소')),
                ('도로명주소', models.CharField(blank=True, max_length=200, null=True, verbose_name='도로명 주소')),
                ('지번주소', models.CharField(blank=True, max_length=200, null=True, verbose_name='지번 주소')),
                ('상세주소', models.CharField(blank=True, max_length=200, null=True, verbose_name='상세 주소 (동/호수)')),
                ('위도', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='위도 좌표')),
                ('경도', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='경도 좌표')),
                ('월관리비', models.IntegerField(blank=True, null=True, verbose_name='월 관리비(원)')),
                ('관리비포함항목', models.TextField(blank=True, null=True, verbose_name='관리비 포함 항목')),
                ('주차정보', models.TextField(blank=True, null=True, verbose_name='주차 정보')),
                ('전용면적_제곱미터', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='전용면적(㎡)')),
                ('전용면적_평', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='전용면적(평)')),
                ('방수', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='방 개수')),
                ('욕실수', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='욕실 개수')),
                ('층수', models.CharField(blank=True, max_length=20, null=True, verbose_name='층수 정보')),
                ('현재층', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='현재 층')),
                ('총층수', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='총 층수')),
                ('준공년도', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='준공 연도')),
                ('공급면적_제곱미터', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='공급면적(㎡)')),
                ('방향', models.CharField(blank=True, max_length=10, null=True, verbose_name='방향')),
                ('총세대수', models.PositiveIntegerField(blank=True, null=True, verbose_name='총 세대수')),
                ('총주차대수', models.PositiveIntegerField(blank=True, null=True, verbose_name='총 주차대수')),
                ('현관유형', models.CharField(blank=True, max_length=20, null=True, verbose_name='현관 유형')),
                ('입주가능일', models.CharField(blank=True, max_length=50, null=True, verbose_name='입주 가능일')),
                ('건축물용도', models.CharField(blank=True, max_length=50, null=True, verbose_name='건축물 용도')),
                ('사용승인일', models.DateField(blank=True, null=True, verbose_name='사용승인일')),
                ('최초등록일', models.DateField(blank=True, null=True, verbose_name='최초 등록일')),
                ('계약기간_개월', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='계약 기간(개월)')),
                ('재계약가능여부', models.BooleanField(blank=True, null=True, verbose_name='재계약 가능 여부')),
                ('매물상태', models.CharField(choices=[('available', '모집중'), ('viewing', '임장예약중'), ('contracted', '계약완료'), ('sold', '거래완료')], default='available', max_length=20, verbose_name='매물 상태')),
                ('상세설명', models.TextField(blank=True, null=True, verbose_name='매물 상세 설명')),
                ('조회수', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('찜수', models.PositiveIntegerField(default=0, verbose_name='찜 개수')),
                ('활성화여부', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('생성일시', models.DateTimeField(auto_now_add=True, verbose_name='등록 일시')),
                ('수정일시', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('관리중개사ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_listings', to='agents.agent', verbose_name='관리 중개사')),
                ('등록사용자ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_listings', to='users.userprofile', verbose_name='등록한 사용자 프로필')),
                ('지역ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region', verbose_name='지역 정보')),
            ],
            options={
                'verbose_name': '매물',
                'verbose_name_plural': '매물',
                'db_table': 'listings',
                'ordering': ['-생성일시'],
            },
        ),
    ]
