# Generated by Django 5.2.6 on 2025-10-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_qa정보_listing_노선다양성점수_listing_대중교통점수_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='QA정보',
            field=models.JSONField(blank=True, null=True, verbose_name='Q&A 정보'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='버스정류장정보',
            field=models.JSONField(blank=True, null=True, verbose_name='버스 정류장 정보'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='이미지URLs',
            field=models.JSONField(blank=True, null=True, verbose_name='매물 이미지 URL 목록'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='지하철역정보',
            field=models.JSONField(blank=True, null=True, verbose_name='지하철역 정보'),
        ),
    ]
