# Generated by Django 5.2.6 on 2025-10-15 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('사용자유형', models.CharField(choices=[('user', '일반회원'), ('agent', '중개사')], default='user', max_length=20, verbose_name='사용자 유형')),
                ('연락처', models.CharField(blank=True, max_length=20, null=True, verbose_name='휴대폰 번호')),
                ('프로필이미지URL', models.TextField(blank=True, null=True, verbose_name='프로필 이미지 URL')),
                ('활성화여부', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='연결된 사용자')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필',
                'db_table': 'user_profiles',
            },
        ),
    ]
