# Generated by Django 5.2.6 on 2025-10-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='귀촌목적',
            field=models.CharField(blank=True, choices=[('귀어', '귀어'), ('귀농', '귀농'), ('취업', '취업'), ('기타', '기타')], max_length=10, null=True, verbose_name='귀촌 목적'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='선호지역목록',
            field=models.JSONField(blank=True, null=True, verbose_name='관심 지역 목록'),
        ),
    ]
